name: pluto_grid
description: PlutoGrid is a dataGrid that can be controlled by the keyboard on
  desktop and web. Of course, it works well on Android and IOS. (DataGrid,
  DataTable, Data Grid, Data Table, Sticky)
version: 8.0.0
homepage: https://pluto.weblaze.dev
repository: https://github.com/bosskmk/pluto_grid

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
